name: CI/CD Workflow

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
   branches:
     - '**'

jobs:
  pre-commit-scans:
    runs-on: ubuntu-latest
    steps:
       - name: Setup Java
         uses: actions/setup-java@v4
         with:
           distribution: 'temurin'
           java-version: '21'

       - name: Checkout code
         uses: actions/checkout@v4

       - name: Perform google formatter check
         if: false
         run: mvn com.spotify.fmt:fmt-maven-plugin:check

       - name: GitLeaks Scan
         uses: zricethezav/gitleaks-action@v1.3.0
         with:
           args: --path=.

       - name: OSS Scan
         run: mvn ossindex:audit
         continue-on-error: true

       - name: OWASP Scan
         if: false
         run: mvn org.owasp:dependency-check-maven:check

       - name: Build Code and create docker image
         run: mvn clean install docker:build -Dimage.registry=${{vars.CONTAINER_REGISTRY_USER}} -Dimage.tag=$GITHUB_REF_NAME

       - name: Login to Docker Hub Resgistry
         uses: docker/login-action@v3
         with:
           username: ${{vars.DOCKER_REGISTRY_USER}}
           password: ${{secrets.DOCKER_REGISTRY_PAT}}
            
       - name: Push Docker Image
         run: docker push ${{vars.CONTAINER_REGISTRY_USER}}/api-gateway:$GITHUB_REF_NAME
         
