name: Api-Gateway github action

on:
  push:
    branches:
      - main

jobs:
  api-gateway:
    runs-on: ubuntu-latest
    container:
      image: maven:latest
    steps:
       - name: open-jdk install
         run: apt-get install -y openjdk-17-jdk
       - name: Run Maven clean install
         run: mvn clean install
